[package]
name = "rillrate-logs-protocol"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/rillrate/logs"
homepage = "https://github.com/rillrate/logs"
documentation = "https://docs.rs/rillrate-logs-protocol/"
license = "Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "RillRate agent for logging"

[dependencies]
